CREATE TABLE SOPORTEDBA.LOG_ENMASCARADO
(
  RUN_ID             RAW(16)                    DEFAULT SYS_GUID()            NOT NULL,
  START_TS           TIMESTAMP(6)               NOT NULL,
  END_TS             TIMESTAMP(6),
  OWNER_NAME         VARCHAR2(128 BYTE),
  TABLE_NAME         VARCHAR2(128 BYTE),
  OP_LABEL           VARCHAR2(50 BYTE),
  MERGED_COUNT       NUMBER,
  BACKFILLED_COUNT   NUMBER,
  MISSING_AFTER_TMT  NUMBER,
  SESSION_ID         NUMBER,
  MODULE             VARCHAR2(64 BYTE),
  ACTION             VARCHAR2(64 BYTE),
  ERR_CODE           NUMBER,
  ERR_MSG            VARCHAR2(4000 BYTE),
  ERR_STACK          CLOB,
  ERR_CALLSTACK      CLOB,
  NOTES              VARCHAR2(4000 BYTE)
)
LOB (ERR_CALLSTACK) STORE AS SECUREFILE (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
LOB (ERR_STACK) STORE AS SECUREFILE (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE SOPORTEDBA.LOG_ENMASCARADO IS 'Registro de ejecuciones del proceso de enmascarado (runs): tiempos, métricas, sesión y errores.';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.RUN_ID IS 'ID único del run de enmascarado. Generado con SYS_GUID() al iniciar.';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.START_TS IS 'Timestamp de inicio del run.';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.END_TS IS 'Timestamp de fin del run (éxito o error).';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.OWNER_NAME IS 'Esquema fuente (p_owner) sobre el que corre el run (ej. PROD_ENTIDAD700).';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.TABLE_NAME IS 'Tabla fuente específica cuando el proceso es por tabla; NULL si es general.';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.OP_LABEL IS 'Operación/mode del run: REFRESH (full) o INCREMENTAL.';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.MERGED_COUNT IS 'Filas afectadas por la construcción/actualización de TMT o merges principales.';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.BACKFILLED_COUNT IS 'Filas insertadas por el backfill post-TMT (faltantes).';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.MISSING_AFTER_TMT IS 'Cantidad de claves faltantes luego del backfill (idealmente 0).';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.SESSION_ID IS 'ID de sesión Oracle (USERENV(''SESSIONID'')).';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.MODULE IS 'Módulo de aplicación (DBMS_APPLICATION_INFO.SET_MODULE / USERENV MODULE).';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.ACTION IS 'Acción/etapa dentro del módulo (USERENV ACTION).';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.ERR_CODE IS 'Código de error Oracle si el run falló (SQLCODE).';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.ERR_MSG IS 'Mensaje corto del error (SQLERRM).';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.ERR_STACK IS 'Backtrace del error con línea exacta (DBMS_UTILITY.FORMAT_ERROR_BACKTRACE).';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.ERR_CALLSTACK IS 'Pila de llamadas (DBMS_UTILITY.FORMAT_CALL_STACK).';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO.NOTES IS 'Notas libres del run: parámetros de ejecución, hints, etc.';


CREATE UNIQUE INDEX SOPORTEDBA.PK_LOG_ENMASCARADO ON SOPORTEDBA.LOG_ENMASCARADO
(RUN_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SOPORTEDBA.LOG_ENMASCARADO ADD (
  CONSTRAINT PK_LOG_ENMASCARADO
  PRIMARY KEY
  (RUN_ID)
  USING INDEX SOPORTEDBA.PK_LOG_ENMASCARADO
  ENABLE VALIDATE);


CREATE INDEX SOPORTEDBA.IX_LOG_ENMASC_OP ON SOPORTEDBA.LOG_ENMASCARADO
(OWNER_NAME, OP_LABEL, START_TS)
NOLOGGING
TABLESPACE TS_INDICES01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER INDEX SOPORTEDBA.IX_LOG_ENMASC_OP
  MONITORING USAGE;

CREATE INDEX SOPORTEDBA.IX_LOG_ENMASC_START ON SOPORTEDBA.LOG_ENMASCARADO
(START_TS)
NOLOGGING
TABLESPACE TS_INDICES01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER INDEX SOPORTEDBA.IX_LOG_ENMASC_START
  MONITORING USAGE;


CREATE TABLE SOPORTEDBA.LOG_ENMASCARADO_DET
(
  DETAIL_ID       RAW(16)      DEFAULT SYS_GUID() NOT NULL,
  RUN_ID          RAW(16)                          NOT NULL,
  STAGE_NAME      VARCHAR2(80 BYTE)                NOT NULL,
  OWNER_NAME      VARCHAR2(128 BYTE),
  TABLE_NAME      VARCHAR2(128 BYTE),
  START_TS        TIMESTAMP(6),
  END_TS          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  ELAPSED_SECONDS NUMBER,
  ROWS_PROCESSED  NUMBER,
  STATUS          VARCHAR2(20 BYTE) DEFAULT 'OK'   NOT NULL,
  ERR_CODE        NUMBER,
  ERR_MSG         VARCHAR2(4000 BYTE),
  NOTES           VARCHAR2(4000 BYTE)
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;

COMMENT ON TABLE SOPORTEDBA.LOG_ENMASCARADO_DET IS 'Detalle por etapa del proceso de enmascarado: carga STG, TMT, merges por tabla, tiempos y filas.';

COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO_DET.DETAIL_ID IS 'ID único del registro de detalle.';
COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO_DET.RUN_ID IS 'ID del run principal en LOG_ENMASCARADO.';
COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO_DET.STAGE_NAME IS 'Nombre de la etapa registrada: TMT_MERGE, STG_LOAD, MERGE_TABLE, etc.';
COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO_DET.OWNER_NAME IS 'Esquema fuente procesado.';
COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO_DET.TABLE_NAME IS 'Tabla asociada a la etapa, cuando aplica.';
COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO_DET.START_TS IS 'Timestamp de inicio de la etapa.';
COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO_DET.END_TS IS 'Timestamp de fin de la etapa.';
COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO_DET.ELAPSED_SECONDS IS 'Duración aproximada de la etapa en segundos.';
COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO_DET.ROWS_PROCESSED IS 'Filas insertadas, levantadas o actualizadas por la etapa.';
COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO_DET.STATUS IS 'Estado de la etapa: OK, ERROR, WARN, SKIP.';
COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO_DET.ERR_CODE IS 'Código Oracle si la etapa falló o emitió advertencia.';
COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO_DET.ERR_MSG IS 'Mensaje de error o advertencia de la etapa.';
COMMENT ON COLUMN SOPORTEDBA.LOG_ENMASCARADO_DET.NOTES IS 'Notas libres de la etapa.';

CREATE UNIQUE INDEX SOPORTEDBA.PK_LOG_ENMASCARADO_DET ON SOPORTEDBA.LOG_ENMASCARADO_DET
(DETAIL_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SOPORTEDBA.LOG_ENMASCARADO_DET ADD (
  CONSTRAINT PK_LOG_ENMASCARADO_DET
  PRIMARY KEY
  (DETAIL_ID)
  USING INDEX SOPORTEDBA.PK_LOG_ENMASCARADO_DET
  ENABLE VALIDATE);

ALTER TABLE SOPORTEDBA.LOG_ENMASCARADO_DET ADD (
  CONSTRAINT FK_LOG_ENMASC_DET_RUN
  FOREIGN KEY (RUN_ID)
  REFERENCES SOPORTEDBA.LOG_ENMASCARADO (RUN_ID)
  ENABLE VALIDATE);

CREATE INDEX SOPORTEDBA.IX_LOG_ENMASC_DET_RUN ON SOPORTEDBA.LOG_ENMASCARADO_DET
(RUN_ID, END_TS)
NOLOGGING
TABLESPACE TS_INDICES01;

ALTER INDEX SOPORTEDBA.IX_LOG_ENMASC_DET_RUN
  MONITORING USAGE;

CREATE INDEX SOPORTEDBA.IX_LOG_ENMASC_DET_STAGE ON SOPORTEDBA.LOG_ENMASCARADO_DET
(OWNER_NAME, STAGE_NAME, TABLE_NAME, END_TS)
NOLOGGING
TABLESPACE TS_INDICES01;

ALTER INDEX SOPORTEDBA.IX_LOG_ENMASC_DET_STAGE
  MONITORING USAGE;
