DROP TABLE SOPORTEDBA.STG_CT_RIDS CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE SOPORTEDBA.STG_CT_RIDS
(
  RID           UROWID(4000),
  CT_NORM       VARCHAR2(200 BYTE),
  TABLA_ORIGEN  VARCHAR2(30 BYTE),
  CT_NEW        VARCHAR2(64 BYTE),
  MASK_NEW      VARCHAR2(40 BYTE),
  RID_UROWID    UROWID(4000)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


CREATE INDEX SOPORTEDBA.IX_STG_CT_NORM ON SOPORTEDBA.STG_CT_RIDS
(CT_NORM);

CREATE INDEX SOPORTEDBA.IX_STG_CT_RIDS_RIDU ON SOPORTEDBA.STG_CT_RIDS
(TABLA_ORIGEN, RID_UROWID);

CREATE INDEX SOPORTEDBA.IX_STG_CT_RIDS_TAB_RID ON SOPORTEDBA.STG_CT_RIDS
(TABLA_ORIGEN, RID);


DROP TABLE SOPORTEDBA.STG_PAN_UNICOS CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE SOPORTEDBA.STG_PAN_UNICOS
(
  CT_NORM   VARCHAR2(256 BYTE),
  BUCKET_ID NUMBER,
  FECHA_ALTA TIMESTAMP(6) DEFAULT SYSTIMESTAMP
)
ON COMMIT PRESERVE ROWS
NOCACHE;


CREATE INDEX SOPORTEDBA.IX_STG_PAN_UNICOS_CT ON SOPORTEDBA.STG_PAN_UNICOS
(CT_NORM);

CREATE INDEX SOPORTEDBA.IX_STG_PAN_UNICOS_BUCKET ON SOPORTEDBA.STG_PAN_UNICOS
(BUCKET_ID, CT_NORM);
