DROP TABLE SOPORTEDBA.COMPROBACION CASCADE CONSTRAINTS;

CREATE TABLE SOPORTEDBA.COMPROBACION
(
  NRO_TARJETA_ENCRIPTADA           VARCHAR2(256 BYTE),
  NRO_TARJETA_DESENCRIPTADA        VARCHAR2(256 BYTE),
  NRO_TARJETA_ENCRIPTADA_NUEVA     VARCHAR2(256 BYTE),
  NRO_TARJETA_DESENCRIPTADA_NUEVA  VARCHAR2(256 BYTE)
)