DROP TABLE SOPORTEDBA.TABLA_MAESTRA_TARJETAS CASCADE CONSTRAINTS;

CREATE TABLE SOPORTEDBA.TABLA_MAESTRA_TARJETAS
(
  NRO_TARJETA_ENCRIPTADA_ORIGINAL  VARCHAR2(256 BYTE),
  NRO_TARJETA_DESENCRIPTADA        VARCHAR2(256 BYTE),
  NRO_TARJETA_ENMASCARADA_NUEVA    VARCHAR2(256 BYTE),
  NRO_TARJETA_MODIFICADA           VARCHAR2(256 BYTE),
  NRO_TARJETA_ENCRIPTADA_NUEVA     VARCHAR2(256 BYTE),
  FECHA_ALTA                       TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  FUENTE                           VARCHAR2(30 CHAR)
);

CREATE INDEX SOPORTEDBA.IX_TMT_CT_NEW ON SOPORTEDBA.TABLA_MAESTRA_TARJETAS
(NRO_TARJETA_ENCRIPTADA_NUEVA)
TABLESPACE TS_INDICES01 ONLINE NOLOGGING;

ALTER INDEX SOPORTEDBA.IX_TMT_CT_NEW MONITORING USAGE;

CREATE INDEX SOPORTEDBA.IX_TMT_CT_ORIG ON SOPORTEDBA.TABLA_MAESTRA_TARJETAS
(NRO_TARJETA_ENCRIPTADA_ORIGINAL)
TABLESPACE TS_INDICES01 ONLINE NOLOGGING;

ALTER INDEX SOPORTEDBA.IX_TMT_CT_ORIG MONITORING USAGE;




