-- <<< Parámetro de esquema de entidad >>>
-- Definí el esquema de entidad al ejecutar el script.
DEFINE P_OWNER = 'YOUR_ENTITY_SCHEMA';

--------------------------------------------------
-- GRANTS / SYNONYM PAN_CRYPTO
--------------------------------------------------

GRANT EXECUTE ON SOPORTEDBA.PAN_CRYPTO TO &P_OWNER;

CREATE OR REPLACE SYNONYM &P_OWNER..PAN_CRYPTO
  FOR SOPORTEDBA.PAN_CRYPTO;

--------------------------------------------------
-- GRANTS DE LECTURA DESDE EL ESQUEMA PARAMETRIZADO
-- (&P_OWNER) HACIA SOPORTEDBA
--------------------------------------------------

GRANT INSERT, SELECT, UPDATE ON &P_OWNER..AUTORIZACION TO SOPORTEDBA;
GRANT INSERT, SELECT, UPDATE ON &P_OWNER..AUTORIZACION_ADQUIRENTE_LOG TO SOPORTEDBA;
GRANT INSERT, SELECT, UPDATE ON &P_OWNER..AUTORIZACION_CONSULTA TO SOPORTEDBA;
GRANT INSERT, SELECT, UPDATE ON &P_OWNER..CONSUMOS TO SOPORTEDBA;
GRANT INSERT, SELECT, UPDATE ON &P_OWNER..IPM TO SOPORTEDBA;
GRANT INSERT, SELECT, UPDATE ON &P_OWNER..RESPUESTA_MC_LOG TO SOPORTEDBA;
GRANT INSERT, SELECT, UPDATE ON &P_OWNER..TQR4_ADQUIRENCIA TO SOPORTEDBA;
GRANT INSERT, SELECT, UPDATE ON &P_OWNER..TC33A TO SOPORTEDBA;
