-- =========================================================
-- PARAMETROS
-- =========================================================
DEFINE OWNER = ENTIDAD700
DEFINE TBS   = TS_INDICES01

SET DEFINE ON
SET SERVEROUTPUT ON
SET VERIFY OFF


-- =========================================================
-- DROP (safe) - no falla si el índice no existe
-- =========================================================
DECLARE
  PROCEDURE drop_idx(p_idx IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX &&OWNER.' || p_idx;
    DBMS_OUTPUT.PUT_LINE('DROP OK: ' || '&&OWNER.' || p_idx);
  EXCEPTION
    WHEN OTHERS THEN
      -- ORA-01418: specified index does not exist
      IF SQLCODE = -1418 THEN
        DBMS_OUTPUT.PUT_LINE('DROP SKIP (no existe): ' || '&&OWNER.' || p_idx);
      ELSE
        DBMS_OUTPUT.PUT_LINE('DROP ERROR: ' || '&&OWNER.' || p_idx || ' -> ' || SQLERRM);
        RAISE;
      END IF;
  END;
BEGIN
  drop_idx('IDX_AUT_NROTARJ');
  drop_idx('IDX_AUTCONS_NROTARJ');
  drop_idx('IDX_IPM_NROTARJ');
  drop_idx('IDX_RTA_MCLOG_NROTARJ');
  drop_idx('IDX_TQR4ADQ_NROTARJ');
  drop_idx('IDX_TC33A_IDTC33A');
END;
/

-- =========================================================
-- CREATE + MONITORING USAGE
-- =========================================================

-- AUTORIZACION
CREATE INDEX &&OWNER..IDX_AUT_NROTARJ
ON &&OWNER..AUTORIZACION (NRO_TARJETA)
TABLESPACE &&TBS ONLINE NOLOGGING;

ALTER INDEX &&OWNER..IDX_AUT_NROTARJ MONITORING USAGE;

-- AUTORIZACION_CONSULTA
CREATE INDEX &&OWNER..IDX_AUTCONS_NROTARJ
ON &&OWNER..AUTORIZACION_CONSULTA (NRO_TARJETA)
TABLESPACE &&TBS ONLINE NOLOGGING;

ALTER INDEX &&OWNER..IDX_AUTCONS_NROTARJ MONITORING USAGE;

-- IPM
CREATE INDEX &&OWNER..IDX_IPM_NROTARJ
ON &&OWNER..IPM (NRO_TARJETA)
TABLESPACE &&TBS ONLINE NOLOGGING;

ALTER INDEX &&OWNER..IDX_IPM_NROTARJ MONITORING USAGE;

-- RESPUESTA_MC_LOG
CREATE INDEX &&OWNER..IDX_RTA_MCLOG_NROTARJ
ON &&OWNER..RESPUESTA_MC_LOG (IN_NRO_TARJETA)
TABLESPACE &&TBS ONLINE NOLOGGING;

ALTER INDEX &&OWNER..IDX_RTA_MCLOG_NROTARJ MONITORING USAGE;

-- TQR4_ADQUIRENCIA
CREATE INDEX &&OWNER..IDX_TQR4ADQ_NROTARJ
ON &&OWNER..TQR4_ADQUIRENCIA (NRO_TARJETA)
TABLESPACE &&TBS ONLINE NOLOGGING;

ALTER INDEX &&OWNER..IDX_TQR4ADQ_NROTARJ MONITORING USAGE;

-- TC33A (para actualizar NRO_TARJETA_ENMASCARADA via CONSUMOS)
CREATE INDEX &&OWNER..IDX_TC33A_IDTC33A
ON &&OWNER..TC33A (ID_TC33A)
TABLESPACE &&TBS ONLINE NOLOGGING;

ALTER INDEX &&OWNER..IDX_TC33A_IDTC33A MONITORING USAGE;


