DEFINE P_OWNER = 'ENTIDAD703';
DEFINE P_DEG   = 2;

ALTER SESSION ENABLE PARALLEL DML;

--------------------------------------
-- 1) AUTORIZACION
--------------------------------------
MERGE /*+ PARALLEL(a,&P_DEG) */ INTO &P_OWNER..AUTORIZACION a
USING (
  SELECT /*+ USE_HASH(a tm) PARALLEL(tm,&P_DEG) PARALLEL(a,&P_DEG) */
         a.ROWID                          AS rid,
         tm.NRO_TARJETA_ENMASCARADA_NUEVA AS mask_new
  FROM   &P_OWNER..AUTORIZACION a
  JOIN   SOPORTEDBA.TABLA_MAESTRA_TARJETAS tm
         ON tm.NRO_TARJETA_ENCRIPTADA_NUEVA = a.NRO_TARJETA
  WHERE  tm.NRO_TARJETA_ENMASCARADA_NUEVA IS NOT NULL
) s
ON (a.ROWID = s.rid)
WHEN MATCHED THEN UPDATE SET
  a.NRO_TARJETA_ENMASCARADA = s.mask_new
WHERE
     a.NRO_TARJETA_ENMASCARADA <> s.mask_new
  OR (a.NRO_TARJETA_ENMASCARADA IS NULL AND s.mask_new IS NOT NULL)
  OR (a.NRO_TARJETA_ENMASCARADA IS NOT NULL AND s.mask_new IS NULL);

COMMIT;

--------------------------------------
-- 2) AUTORIZACION_CONSULTA
--------------------------------------
MERGE /*+ PARALLEL(ac,&P_DEG) */ INTO &P_OWNER..AUTORIZACION_CONSULTA ac
USING (
  SELECT /*+ USE_HASH(ac tm) PARALLEL(tm,&P_DEG) PARALLEL(ac,&P_DEG) */
         ac.ROWID                         AS rid,
         tm.NRO_TARJETA_ENMASCARADA_NUEVA AS mask_new
  FROM   &P_OWNER..AUTORIZACION_CONSULTA ac
  JOIN   SOPORTEDBA.TABLA_MAESTRA_TARJETAS tm
         ON tm.NRO_TARJETA_ENCRIPTADA_NUEVA = ac.NRO_TARJETA
  WHERE  tm.NRO_TARJETA_ENMASCARADA_NUEVA IS NOT NULL
) s
ON (ac.ROWID = s.rid)
WHEN MATCHED THEN UPDATE SET
  ac.NRO_TARJETA_ENMASCARADA = s.mask_new
WHERE
     ac.NRO_TARJETA_ENMASCARADA <> s.mask_new
  OR (ac.NRO_TARJETA_ENMASCARADA IS NULL AND s.mask_new IS NOT NULL)
  OR (ac.NRO_TARJETA_ENMASCARADA IS NOT NULL AND s.mask_new IS NULL);

COMMIT;

--------------------------------------
-- 3) TC33A (via CONSUMOS)
--------------------------------------
MERGE /*+ PARALLEL(tc,&P_DEG) */ INTO &P_OWNER..TC33A tc
USING (
  SELECT /*+ USE_HASH(tm c tc) PARALLEL(tm,&P_DEG) PARALLEL(tc,&P_DEG) */
         tc.ROWID                         AS rid,
         tm.NRO_TARJETA_ENMASCARADA_NUEVA AS mask_new
  FROM   &P_OWNER..TC33A    tc
  JOIN   &P_OWNER..CONSUMOS c
         ON c.ID_CONSUMO = tc.ID_TC33A
  JOIN   SOPORTEDBA.TABLA_MAESTRA_TARJETAS tm
         ON tm.NRO_TARJETA_ENCRIPTADA_ORIGINAL = c.NRO_TARJETA
  WHERE  tm.NRO_TARJETA_ENMASCARADA_NUEVA IS NOT NULL
  -- AND    tm.NRO_TARJETA_ENMASCARADA_NUEVA <> 'INVALIXCARD'  -- si algún día lo quisieras
) s
ON (tc.ROWID = s.rid)
WHEN MATCHED THEN UPDATE SET
  tc.NRO_TARJETA_ENMASCARADA = s.mask_new
WHERE
     tc.NRO_TARJETA_ENMASCARADA <> s.mask_new
  OR (tc.NRO_TARJETA_ENMASCARADA IS NULL AND s.mask_new IS NOT NULL)
  OR (tc.NRO_TARJETA_ENMASCARADA IS NOT NULL AND s.mask_new IS NULL);

COMMIT;
